#include "ble.h"

#define BT_ADLD_CONFIG_SERVICE              0x0100
#define BT_ADLD_CONFIG_DEVICE_NAME_CHAR     0x0102
#define BT_ADLD_CONFIG_LOCATION_CHAR        0x0103

#define BT_ADLD_CONFIG_FILE_TRANSFER_CHAR   0x0109

#define BT_UUID_CONFIG_SERVICE_VAL \
    BT_UUID_128_ENCODE(BT_ADLD_SPECIFIC_UUID_FIRST + BT_ADLD_CONFIG_SERVICE, BT_ADLD_SPECIFIC_UUID_SECOND, BT_ADLD_SPECIFIC_UUID_THIRD, BT_ADLD_SPECIFIC_UUID_FOURTH, BT_ADLD_SPECIFIC_UUID_LAST)

#define BT_UUID_CHRC_DEVICE_NAME_VAL \
    BT_UUID_128_ENCODE(BT_ADLD_SPECIFIC_UUID_FIRST + BT_ADLD_CONFIG_DEVICE_NAME_CHAR, BT_ADLD_SPECIFIC_UUID_SECOND, BT_ADLD_SPECIFIC_UUID_THIRD, BT_ADLD_SPECIFIC_UUID_FOURTH, BT_ADLD_SPECIFIC_UUID_LAST)

#define BT_UUID_CHRC_LOCATION_VAL \
    BT_UUID_128_ENCODE(BT_ADLD_SPECIFIC_UUID_FIRST + BT_ADLD_CONFIG_LOCATION_CHAR, BT_ADLD_SPECIFIC_UUID_SECOND, BT_ADLD_SPECIFIC_UUID_THIRD, BT_ADLD_SPECIFIC_UUID_FOURTH, BT_ADLD_SPECIFIC_UUID_LAST)
    
#define BT_UUID_CHRC_FILE_TRANSFER_VAL \
    BT_UUID_128_ENCODE(BT_ADLD_SPECIFIC_UUID_FIRST + BT_ADLD_CONFIG_FILE_TRANSFER_CHAR, BT_ADLD_SPECIFIC_UUID_SECOND, BT_ADLD_SPECIFIC_UUID_THIRD, BT_ADLD_SPECIFIC_UUID_FOURTH, BT_ADLD_SPECIFIC_UUID_LAST)

#define BT_UUID_CONFIG_SERVICE              BT_UUID_DECLARE_128(BT_UUID_CONFIG_SERVICE_VAL)
#define BT_UUID_CHRC_DEVICE_NAME            BT_UUID_DECLARE_128(BT_UUID_CHRC_DEVICE_NAME_VAL)
#define BT_UUID_CHRC_LOCATION               BT_UUID_DECLARE_128(BT_UUID_CHRC_LOCATION_VAL)
#define BT_UUID_CHRC_FILE_TRANSFER          BT_UUID_DECLARE_128(BT_UUID_CHRC_FILE_TRANSFER_VAL)

typedef struct device_config_s {
    char device_name[30];
    char location[30];
    uint8_t update_flag;
} device_config_t;

extern device_config_t dean_device_conf;
int get_dean_device_config(device_config_t *conf);

// BLE file transfer cmd
#define BLE_FILE_TRANSFER_CMD_START 1
#define BLE_FILE_TRANSFER_CMD_DATA 2
#define BLE_FILE_TRANSFER_CMD_END 3
#define BLE_FILE_TRANSFER_CMD_REMOVE 4
#define BLE_FILE_TRANSFER_CMD_FAILED 11

#define BLE_FILE_TRANSFER_FRAME_SIZE 128
struct ble_file_transfer_data_packet
{
    uint8_t cmd;
    uint16_t seq;
    uint16_t size;
    uint8_t data[BLE_FILE_TRANSFER_FRAME_SIZE];
} __attribute__((packed));

struct ble_file_transfer_ack_packet
{
    uint8_t cmd;
    uint16_t seq;
} __attribute__((packed));

void process_file_transfer_write(const void *buf, uint16_t len);
